version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: vindhellfest-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data # volumes persistant
      - ./bd/init:/docker-entrypoint-initdb.d # Pour les scripts d'initialisation
    networks:
      - app-net # Permet au backend de l’appeler via le hostname db
    healthcheck: # Toutes les 10 secondes, Docker vérifie si Postgres répond. Si la base n’est pas prête elle est considérée comme “unhealthy”. Eviter que le backend démarre avant que la BDD soit prête
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
      target: dev  
    container_name: vindhellfest-backend
    restart: always
    env_file:
      - .env
      - .env.backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "4000:4000"
    volumes:
      - ./apps/backend:/app         
      - /app/node_modules           
    networks:
      - app-net  

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
      target: dev
    container_name: vindhellfest-frontend
    restart: always
    env_file:
      - .env
      - .env.frontend
    environment:
      - WATCHPACK_POLLING=true
      - WATCHPACK_POLLING_INTERVAL=1000
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
      - NEXT_DISABLE_TURBOPACK=1
    command: ["npm", "run", "dev", "--", "--webpack", "-H", "0.0.0.0", "-p", "3000"]
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - app-net

networks:
  app-net: # Déclare un réseau Docker interne nommé app-net

volumes:
  pgdata: # Volume persistant pour les données PostgreSQL
